ifndef::imagesdir[:imagesdir: ../images]

// TODO: Übersicht über die Problemstellung (Auftrag und Ziel).

[[section-introduction-and-goals]]
== Introduction and Goals
Ziel des Projekts ist die Entwicklung einer Simulationsumgebung für den MyPalletizer 260 M5, einem Roboterarm, der primär für das erlernen vom Programmieren von Roboterärmen gedacht ist. Der digitale Zwilling soll die physische Maschine realistisch abbilden und es ermöglichen, verschiedene Szenarien zu simulieren und visuell zu analysieren. Ziel ist es, dass Studenten und Fachleute den Roboterarm in einer virtuellen Umgebung testen und optimieren können, bevor sie ihn in der realen Welt einsetzen. Zudem besitzt die Hochschule Luzern bereits zwei MyPalletizer 260 M5, welche jedoch nicht für alle Studentenprojekte ausreichen. Durch die Entwicklung eines digitalen Zwillings können mehr Studenten von der Möglichkeit profitieren, mit dem Roboterarm zu arbeiten, ohne auf die physische Hardware angewiesen zu sein und somit die Lernmöglichkeiten erweitern.

Zudem ist die Simulation öffentlich zugänglich, was es ermöglicht, dass auch Personen ausserhalb der Hochschule Luzern von der Möglichkeit profitieren können, mit dem digitalen Zwilling zu arbeiten und zu lernen. Zudem muss auch kein physischer Roboterarm mehr angeschafft werden, was Kosten spart und somit auch für kleinere Bildungseinrichtungen zugänglich macht oder für privat Personen, die sich für das Programmieren von Roboterarmen interessieren.

=== Functional Requirements
Der Digital Twin für den MyPalletizer 260 M5 soll folgende funktionale Anforderungen erfüllen:

* Für jedes Betriebssystem (Windows, Linux, macOS) verfügbar sein.
* Eine einfache Installation und Konfiguration ermöglichen, um die Simulation schnell und unkompliziert nutzen zu können.
* Realistische Simulation der Bewegungen und Funktionen des MyPalletizer 260 M5.
* Das Programmieren des Roboterarms in der Programmiersprache Python ermöglichen.
* Das Programmierte in der Simulation, auf dem echten Roboterarm oder beides gleichzeitig ausführen können.
* Eine benutzerfreundliche Oberfläche für die Interaktion mit der Simulation bereitstellen.
** Objekte in der Simulation platzieren können, um verschiedene Szenarien zu erstellen.
** Verschiedene Kameraperspektiven und Ansichten der Simulation ermöglichen.
** Eine visuelle Darstellung der Bewegungen und Aktionen des Roboterarms bereitstellen.
** Roboterzubehör wie der Greifer oder der  Saugnapf in der Simulation verwenden können.
* Eine Dokumentation und Tutorials für die Nutzung der Simulation bereitstellen.

=== Quality Goals
Die wichtigsten Qualitätsziele für das Projekt sind:

* **Maintainability**: Einfache Wartung und Erweiterung der Simulation, um zukünftige Anforderungen und Verbesserungen zu ermöglichen.
* **Reliability**: Zuverlässige Simulation, die realistische Ergebnisse liefert und stabil läuft.
* **Testability**: Einfaches Testen der Simulation, um Fehler frühzeitig zu erkennen und zu beheben.
* **Transparency**: Klare Dokumentation und Nachvollziehbarkeit der Architekturentscheidungen.
* **Deployability**: Einfache Bereitstellung und Konfiguration der Simulation auf verschiedenen Plattformen.



