ifndef::imagesdir[:imagesdir: ../images]

// TODO: Randbedingungen, welche bei der Lösung eingehalten werden müssen, z.B. bestehende Systeme, welche unterstützt werden müssen oder spezielle Anforderungen, welche den Lösungsraum einschränken. 

[[section-architecture-constraints]]
== Architecture Constraints
Der Digital Twin für den MyPalletizer 260 M5 Unity Version muss unter Berücksichtigung der folgenden Architektur- und Entwurfsbeschränkungen entwickelt werden:

=== Existing Systems and Supported Platforms
* Das System muss auf den Betriebssystemen Windows, Linux und macOS lauffähig sein, um eine breite Nutzerbasis zu erreichen.
* Die Library für die Ansteuerung des Roboterarms vom Hersteller Elephant Robotics muss verwendet werden, um die Kompatibilität mit der physischen Maschine sicherzustellen.

=== Technical and Architectural Constraints
* Die unterschützte Programmiersprache für das Ansteuern des Roboterarms ist Python, da dies Programmiersprache primär von Studenten und Fachleuten genutzt wird, um Roboterarme zu programmieren. Das implementieren von anderen Programmiersprachen ist nicht vorgesehen, da diese den Projektumfang sprengen würden und die Zielgruppe hauptsächlich Python nutzt.
* Die Simulation muss in der Unity-Engine implementiert werden, da diese eine leistungsstarke und weit verbreitete Plattform für die Entwicklung von 3D-Simulationen ist.
* Nur die funktionalen Funktionen von der Herstellerbibliothek sollten implementiert werden, um die Komplexität zu reduzieren und die Wartbarkeit zu erhöhen. Erweiterte Funktionen oder benutzerdefinierte Funktionen sind nicht vorgesehen, da dies den Projektumfang sprengen würde und die Zielgruppe hauptsächlich die grundlegenden Funktionen benötigt.


=== Development and Testing Constraints
* Das Projekt wird auf einem Github-Repository entwickelt, um die Zusammenarbeit und Versionskontrolle zu gewährleisten.
* Der Quellcode wird kontinuierlich integriert und getestet (CI/CD-Pipeline auf Github).
* Automatisierte Unit- und manuelle Systemtests sind verpflichtend.
* Die Dokumentation der Architekturentscheidungen und des Systemdesigns erfolgt auf der ARC42-Dokumentation.



